### ISSUE TITLE
Contrast in inbox fields

### ISSUE THREAD

**Issue by scenaristeur** [itme/itme.online#10]
Hi all, great job,
I think you should modify contrast in the forms for sending message.
Gray on black is not really clear
![Screenshot_20210211-105959_Chrome](https://user-images.githubusercontent.com/4020744/107623096-1d09c200-6c59-11eb-93ed-fb281bea9a77.jpg)

**Comment by travis** [comment]
oh lol - forgot that was still exposed, thanks for noticing! we're gonna hide this until we redesign messaging, this was leftovers from the https://face.baby experiment...
