### ISSUE TITLE
Encrypted private notes

### ISSUE THREAD

**Issue by ianconsolata** [itme/itme.online#2]

**Comment by agentydragon** [comment]
I just played a bit with itme.online, for most of my private notes as a user I'd be happy to just have them land in a private section of the Solid storage, wouldn't have to be encrypted.

**Comment by ianconsolata** [comment]
Agreed! Gonna close this for now, this is definitely on our roadmap but it's not something we plan to do anytime in the near term. Private notes are definitely the more immediate goal.
