### ISSUE TITLE
TODO lists seem broken

### ISSUE THREAD

**Issue by agentydragon** [itme/itme.online#3]
I see this error in console when I create a TODO list, and then click on the checkbox:
![image](https://user-images.githubusercontent.com/714892/107091614-5ded7b00-6802-11eb-830d-339c6b319699.png)

The TODO item also does not change state afterwards.

**Comment by travis** [comment]
fixed in https://github.com/itme/itme.online/commit/137c0491eef77694f9402bf86cc7d61d1efb24f8 , will be pushed in 0.3.0 release scheduled for tomorrow!
