### ISSUE TITLE
[BUG] Site down?

### ISSUE THREAD

**Issue by michielbdejong** [itme/itme.online#33]
Looks like https://itme.online is down right now?
https://downforeveryoneorjustme.com/itme.online

**Comment by ianconsolata** [comment]
Hey Michiel! Thanks for pointing that out. We migrated to some new branded urls at understory.garden over the weekend, so I think that was just a DNS propogation issue. If you're still having problems, I'd love to hop on a call with you to debug. I migrated all the data on our NSS server to a new host (myunderstory.com) and we've been having some weird issues that may suggest I did something wrong when rewriting hosts in the .db folder.

**Comment by michielbdejong** [comment]
Thanks!!

**Comment by michielbdejong** [comment]
Updated https://github.com/solid/webmonetization/commit/6644c69bdc635d7f715b703190822bca25a2814f
