### ISSUE TITLE
[Feature Request] Monetize itme.online home page

### ISSUE THREAD

**Issue by inattani** [itme/itme.online#9]
Currently individual notes are monetized, but the user's home page is not. The home page is likely going to become the public profile page that people showcase and share around, and so we should have that fully monetized as well.
![Screen Shot 2021-02-09 at 12 34 09 PM](https://user-images.githubusercontent.com/3708862/107425290-a7281e00-6ad3-11eb-8074-8ded975075a2.png)

**Comment by travis** [comment]
fixed in https://github.com/itme/itme.online/commit/acd465c1d640656ee65495201fe151ce5e8914c4
